name: vnl_common_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  skeletonizer: ^1.4.2
  syntax_highlight: ^0.4.0
  country_flags: ^3.0.0
  phonecodes: ^0.0.3
  cross_file: ^0.3.4+2
  image: ^4.2.0
  web: ^1.0.0
  data_widget: ^0.0.2
  gap: ^3.0.1
  expressions: ^0.2.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icon_font_generator: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
  uses-material-design: true
  fonts:
    - family: RadixIcons
      fonts:
        - asset: "lib/icons/RadixIcons.otf"
    - family: BootstrapIcons
      fonts:
        - asset: "lib/icons/BootstrapIcons.otf"
    - family: LucideIcons
      fonts:
        - asset: "lib/icons/LucideIcons.ttf"
    - family: "GeistSans"
      fonts:
        - asset: "lib/fonts/Geist-Black.otf"
          weight: 800
        - asset: "lib/fonts/Geist-Bold.otf"
          weight: 700
        - asset: "lib/fonts/Geist-Light.otf"
          weight: 300
        - asset: "lib/fonts/Geist-Medium.otf"
          weight: 500
        - asset: "lib/fonts/Geist-SemiBold.otf"
          weight: 600
        - asset: "lib/fonts/Geist-Thin.otf"
          weight: 100
        - asset: "lib/fonts/Geist-UltraBlack.otf"
          weight: 900
        - asset: "lib/fonts/Geist-UltraLight.otf"
          weight: 200
        - asset: "lib/fonts/Geist-Regular.otf"
          weight: 400
    - family: "GeistMono"
      fonts:
        - asset: "lib/fonts/GeistMono-Black.otf"
          weight: 800
        - asset: "lib/fonts/GeistMono-Bold.otf"
          weight: 700
        - asset: "lib/fonts/GeistMono-Light.otf"
          weight: 300
        - asset: "lib/fonts/GeistMono-Medium.otf"
          weight: 500
        - asset: "lib/fonts/GeistMono-Regular.otf"
          weight: 400
        - asset: "lib/fonts/GeistMono-SemiBold.otf"
          weight: 600
        - asset: "lib/fonts/GeistMono-Thin.otf"
          weight: 100
        - asset: "lib/fonts/GeistMono-UltraBlack.otf"
          weight: 900
        - asset: "lib/fonts/GeistMono-UltraLight.otf"
          weight: 200

topics:
  - widgets
  - user-interface
  - design
  - components
  - vnl-ui
